### ISSUE TITLE
Выбор языка программирования

### ISSUE THREAD

**Issue by dkornishev** [Khajiit-Rakaj/Laboratory-of-computational-political-economy#2]
- [ ] Создать список языков-кандидатов (Котлин, питон...)
- [ ] Назначить добровольца для создания доклада по сравнению языков
- [ ] Сделать выбор и задокументировать на вики

Оценка языка должна проводится по множеству критериев, в том числе и надстроечных:

1. Доступность и разнообразность библиотек
2. Системы сборки и запуска
3. Сообщество и накопленная документальная база

**Achtung, panzer!**
 Предложения использования Erlang или Javascript будут рассматриваться только через прицел реактивных
говномётов с зажатой гашеткой.

**Comment by Dipolle** [comment]
Выбор языка программирования предлагаю делать, исходя из того что он должен быть распространенным,бесплатным и свободным для использования, позволять делать как локальные приложения, так и web,по возможности размещать сои приложения и на мобильных платформах, но это очень второстепенно.   Последним требованием является наличие развитого набора инструментов статистического анализа данных, учитывая направление нашей работы. 


На мой взгляд стоит остановится на Python, так как он отвечает всем критериям. Дополнительно придется использовать хотя бы как источник релизации статистических методов среду и язык программирования GNU R в силу его популярности в международных кругах статистиков. 
В качестве IDE предлагю стандартизировать Pycharm community edition
